name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install LFTP
      run: sudo apt-get install -y lftp

    - name: Deploy to FTP server
      env:
        FTP_HOST: ${{ ftp.unmatched.ch}}
        FTP_USERNAME: ${{ wo9ae_unmatched }}
        FTP_PASSWORD: ${{ Q-ZDWgKRs4wrwMg }}
      run: |
        lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -R . /path/to/remote/directory"

